{
 "title": "VMware vSphere  - VMs",
 "description": "VMware vSphere Dashboard using the new Telegraf plugin",
 "tags": [
  "VMware",
  "vSphere VM"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "vcenter",
    "label": "vCenter Server",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=vcenter"
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=clustername"
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=esxhostname"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "SHOW TAG VALUES FROM vsphere_datastore_disk WITH KEY=source"
   },
   {
    "name": "virtualmachine",
    "label": "VM",
    "query": "SHOW TAG VALUES FROM vsphere_vm_cpu WITH KEY=vmname"
   }
  ]
 },
 "panels": [
  { "title": "$virtualmachine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "virtualmachine" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_sys",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage MHz",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "usagemhz_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 1 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "active_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization Avg %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "CPU Utilization %" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "deckbytes", "label": "RAM Usage in GB" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "active_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Ready Avg %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "% CPU Ready Avg." }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "readiness_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "KBs", "label": "Network Usage" }
   ],
   "targets": [
    {
     "alias": "$tag_interface bytesRx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_net",
     "select": [
      [
       { "params": [ "bytesRx_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "$tag_interface bytesTx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_net",
     "select": [
      [
       { "params": [ "bytesTx_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "KBps" }
   ],
   "targets": [
    {
     "alias": "Write - $tag_disk",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "read_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "Read - $tag_disk",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "write_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Adapter Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "numberReadAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "numberWriteAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  }
 ]
}